#
# Blocks of science pipelines
#
scienceBlock:
  -
    name: pipeline_on_brn
    id: "visit=1000^1002^1004^1006^1008^1010"
  -
    name: pipeline_on_bmn
    id: "visit=1001^1003^1005^1007^1009^1011"
